spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    druid:
      initial-size: 5
      max-active: 20
      max-wait: 20000
      min-idle: 1
      validation-query: select 1

# mybatis config
mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mybatis/mapper/*Mapper.xml
server:
  port: 8181
logging:
  config: classpath:logback-spring.xml
